package com.mc.infrastructure.organization.persistence.mapper;

import com.mc.domain.organization.model.entity.Apartment;
import com.mc.infrastructure.organization.persistence.model.ApartmentJpaEntity;
import org.springframework.stereotype.Component;

/**
 * ApartmentPersistenceMapper — Infrastructure Mapper (Organization Context)
 *
 * <p>Translates between the pure domain {@link Apartment} and {@link ApartmentJpaEntity}.
 * Uses the domain's full-arg reconstitution constructor to re-hydrate persisted state.</p>
 */
@Component
public class ApartmentPersistenceMapper {

    /**
     * Converts a domain {@link Apartment} to its JPA entity for persistence.
     *
     * <p>Only set the ID if it exists (for updates). For new entities,
     * the ID was generated by {@code Apartment.create()} via {@link com.mc.domain.core.util.IdUtils}
     * and will be handled by the @GeneratedValue strategy on first flush.</p>
     */
    public ApartmentJpaEntity toEntity(Apartment domain) {
        if (domain == null) return null;

        ApartmentJpaEntity entity = new ApartmentJpaEntity();
        // Only set ID if entity is being updated (ID exists), not for new inserts
        if (domain.getId() != null) {
            entity.setId(domain.getId());
        }
        entity.setName(domain.getName());
        entity.setDescription(domain.getDescription());
        entity.setBackgroundUrl(domain.getBackgroundUrl());
        entity.setOwnerId(domain.getOwnerId());
        entity.setTeamId(domain.getTeamId());
        entity.setCreatedBy(domain.getCreatedBy());
        entity.setWorkspaceId(domain.getWorkspaceId());
        entity.setDeletedBy(domain.getDeletedBy());
        entity.setDeletedAt(domain.getDeletedAt());
        entity.setDeleted(domain.isDeleted());
        return entity;
    }

    /**
     * Reconstitutes a {@link Apartment} domain entity from its JPA entity.
     */
    public Apartment toDomain(ApartmentJpaEntity entity) {
        if (entity == null) return null;

        return new Apartment(
                entity.getId(),
                entity.getName(),
                entity.getDescription(),
                entity.getBackgroundUrl(),
                entity.getOwnerId(),
                entity.getTeamId(),
                entity.getCreatedBy(),
                entity.getWorkspaceId(),
                entity.getDeletedBy(),
                entity.getDeletedAt(),
                entity.getCreatedAt(),
                entity.getUpdatedAt(),
                Boolean.TRUE.equals(entity.getDeleted())
        );
    }
}
