package com.mc.domain.core.model;

import lombok.Getter;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * Base Domain Entity - Pure Domain (no JPA/Framework dependencies)
 * All domain entities should extend this class.
 * 
 * <p>Features:</p>
 * <ul>
 *   <li>UUID-based identity</li>
 *   <li>Audit timestamps (createdAt, updatedAt)</li>
 *   <li>Soft delete support</li>
 *   <li>Proper equals/hashCode based on ID</li>
 * </ul>
 */
@Getter
public abstract class BaseDomainEntity {

    private UUID id;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private boolean deleted;

    // =================================================================
    // CONSTRUCTORS
    // =================================================================
    
    /**
     * Default constructor for new entities.
     * ID will be generated by factory methods.
     */
    protected BaseDomainEntity() {
    }

    /**
     * Constructor for reconstituting existing entities from persistence.
     */
    protected BaseDomainEntity(UUID id, LocalDateTime createdAt, LocalDateTime updatedAt, boolean deleted) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deleted = deleted;
    }

    // =================================================================
    // ID MANAGEMENT
    // =================================================================

    protected void setId(UUID id) {
        this.id = id;
    }

    /**
     * Initialize entity with a new ID and timestamps.
     * Should be called in factory methods when creating new entities.
     */
    protected void initializeNewEntity(UUID id) {
        this.id = id;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
        this.deleted = false;
    }

    // =================================================================
    // AUDIT TIMESTAMPS
    // =================================================================

    /**
     * Mark entity as modified. Should be called when updating entity state.
     */
    protected void markAsModified() {
        this.updatedAt = LocalDateTime.now();
    }

    // =================================================================
    // SOFT DELETE
    // =================================================================

    public void markAsDeleted() {
        this.deleted = true;
        markAsModified();
    }

    public void restore() {
        this.deleted = false;
        markAsModified();
    }

    // =================================================================
    // EQUALS & HASHCODE (ID-based)
    // =================================================================

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BaseDomainEntity that)) return false;
        return id != null && Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        // Use class hashCode for entities without ID yet (transient state)
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{id=" + id + "}";
    }
}
